version: '3'
services:
  client:
    container_name: hotdogs-client
    image: hotdogs-client
    build: ./client
    ports:
      - "80:80"
  server:
    depends_on:
      - mongo
    container_name: hotdogs-server
    image: hotdogs-server
    build: ./server
    ports:
      - "5000:5000"
  mongo:
    image: "mongo"
    container_name: "hotdogs-mongo"
    ports:
      - "27017:27017"
    volumes:
    - data-volume:/data/db
volumes:
  data-volume:
