version: '3'
services:
  client:
    container_name: rcc-client
    image: rcc-client
    build: ./client
    ports:
      - "80:80"
  server:
    depends_on:
      - postgres
    container_name: rcc-server
    image: rcc-server
    build: ./server
    ports:
      - "5000:5000"
    environment: 
      - DB=postgres://postgres:password@postgres:5432/rcc
  postgres:
    image: "postgres:13.1-alpine"
    container_name: "rcc-postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/rcc/dbdata
    environment:
      - POSTGRES_PASSWORD=password
volumes:
  postgres:
