apiVersion: v1
kind: Service
metadata:
  name: database-cluster-ip-service
  labels:
    component: database
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    component: database