apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
  labels:
    component: server
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    component: server